# Generated by Django 3.2.9 on 2021-12-12 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(db_column='_id', primary_key=True, serialize=False)),
                ('surname', models.CharField(blank=True, max_length=40, null=True)),
                ('first_name', models.CharField(blank=True, max_length=40, null=True)),
                ('second_name', models.CharField(blank=True, max_length=40, null=True)),
                ('post', models.CharField(blank=True, max_length=40, null=True)),
                ('salary', models.IntegerField(blank=True, default=15000)),
            ],
            options={
                'db_table': 'employees',
                'managed': True,
            },
        ),
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
        migrations.RenameModel(
            old_name='ItemsShops',
            new_name='ItemShop',
        ),
        migrations.RenameModel(
            old_name='OrdersItems',
            new_name='OrderItem',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='Shops',
            new_name='Shop',
        ),
        migrations.RenameModel(
            old_name='ShopsEmployees',
            new_name='ShopEmployee',
        ),
        migrations.DeleteModel(
            name='Employees',
        ),
        migrations.AddField(
            model_name='employee',
            name='workplace',
            field=models.ForeignKey(blank=True, db_column='workplace', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shop.shop'),
        ),
        migrations.AlterField(
            model_name='order',
            name='courier',
            field=models.ForeignKey(blank=True, db_column='courier', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shop.employee'),
        ),
        migrations.AlterField(
            model_name='shopemployee',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.employee'),
        ),
    ]
